apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-api-sa
  namespace: security-guardian
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: security-guardian
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "networkpolicies"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: security-guardian
subjects:
- kind: ServiceAccount
  name: security-api-sa
  namespace: security-guardian
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
