apiVersion: v1
kind: Pod
metadata:
  name: secure-test-pod
  namespace: security-guardian
spec:
  # Запрещаем запускать контейнер от имени суперпользователя (root)
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - name: secure-container
    image: nginx:alpine
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
